version: '3'
services:
  db:
    image: mysql:8.3
    environment:
      MYSQL_DATABASE: 'campdb'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
  310-project:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/campdb?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    stdin_open: true
    tty: true
    volumes:
      - maven-cache:/root/.m2
      - .:/usr/local/310-project
volumes:
  maven-cache: {}

